INSERT INTO SKILL_STACK (SKILL_NAME) VALUES ('Java');
INSERT INTO SKILL_STACK (SKILL_NAME) VALUES ('JavaScript');
INSERT INTO SKILL_STACK (SKILL_NAME) VALUES ('Spring');
INSERT INTO SKILL_STACK (SKILL_NAME) VALUES ('React');