INSERT INTO skill_stack (SKILL_NAME) VALUES ('Java');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('JavaScript');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Spring');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('React');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('TypeScript');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Figma');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('PostgreSQL');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('React Native');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('HTML');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('CSS');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('MSA');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Amplitude');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Kotlin');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Node.js');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('AWS');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Kubernetes');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('MongoDB');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Angular');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('NestJS');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('JIRA');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('C');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('C++');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Go');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Swift');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Rust');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('PHP');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Perl');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Scala');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Ruby');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Flask');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Express.js');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('ASP.NET');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Laravel');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Symfony');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Spring Boot');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Play');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Ruby on Rails');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('MySQL');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Microsoft SQL Server');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('SQLite');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('MariaDB');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Redis');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Cassandra');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Neo4j');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Couchbase');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Google Cloud Platform');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Microsoft Azure');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('DigitalOcean');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Heroku');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Linode');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Alibaba Cloud');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('IBM Cloud');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Oracle Cloud Infrastructure');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Git');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Jenkins');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Ansible');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Chef');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Puppet');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Nagios');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Grafana');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Kibana');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Spring webflux');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Django');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Dart');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Lua');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('R');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Julia');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Haskell');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Groovy');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Shell Scripting');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Ruby Sinatra');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Phoenix');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('FastAPI');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Vue.js');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Svelte');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Firebase');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('InfluxDB');
INSERT INTO skill_stack (SKILL_NAME) VALUES ('Docker');